*** Settings ***
Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.
...              Functionally accurate but NOT YET production quality: consider
...              refactoring repeated sequences into Layer 2 reusable modules
...              before committing to the suite (see docs/RECORDER_GUIDE.md).
Library          ../api/DriverAgnosticApi.py

*** Test Cases ***
Recorded Session Playback
    [Documentation]    Generated by WpfTestIde.
    Click Element    UnknownPage.gridOrders
