*** Settings ***
Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.
...              Functionally accurate but NOT YET production quality: consider
...              refactoring repeated sequences into Layer 2 reusable modules
...              before committing to the suite (see docs/RECORDER_GUIDE.md).
...              Recording modes: FlaUI, WPFSpy
Library          ../TestAutoLayer/api/DriverAgnosticApi.py

*** Test Cases ***
Recorded Session Playback
    [Documentation]    Generated by WpfTestIde.
    Launch Application    C:/Users/mathe/source/repos/WPFTestAuto/bin/SampleWPFApp/Debug/net9.0-windows/SampleWpfApp.exe    app_id=samplewpfapp    start_in=C:/Users/mathe/source/repos/WPFTestAuto/bin/SampleWPFApp/Debug/net9.0-windows    attach=Yes    drivers=WPFSpy,FlaUI
