*** Settings ***
Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.
...              Functionally accurate but NOT YET production quality: consider
...              refactoring repeated sequences into Layer 2 reusable modules
...              before committing to the suite (see docs/RECORDER_GUIDE.md).
Library          ../api/DriverAgnosticApi.py
Test Setup       Set Driver    WPFSpy

*** Test Cases ***
Recorded Session Playback
    [Documentation]    Generated by WpfTestIde.
    Set Element Value    LoginPage.MainWindow.txtUsername    user1
    Click Element    LoginPage.MainWindow.btnSubmit
