"""
Converter / Generator Tool
============================
Merges the recorder's raw JSON output into:
  1. Element Repository YAML entries (adds a FlaUI strategy block; other
     driver strategies are left for a human to fill in / extend later)
  2. Step Repository YAML entries
  3. A draft Layer 1 Robot Framework test script that calls Layer 3
     (Driver-Agnostic API) keywords directly, in the exact recorded order

This is intentionally "good enough to run, not yet production quality" —
matching the authoring workflow: Record -> Auto-generate -> Add
Verifications -> Refactor to Reusable Modules -> Finalize.
"""

import json
import os
import yaml

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_SAMPLE_DIR = os.path.join(_THIS_DIR, "sample_recorded")
_REPO_ELEMENTS_DIR = os.path.join(_THIS_DIR, "..", "repository", "elements")
_REPO_STEPS_DIR = os.path.join(_THIS_DIR, "..", "repository", "steps")
_DRAFT_TESTS_DIR = os.path.join(_THIS_DIR, "..", "tests")


def _load(name):
    with open(os.path.join(_SAMPLE_DIR, name)) as f:
        return json.load(f)


def generate_element_repository(recorded_elements: dict, out_file="recorded_draft_elements.yaml"):
    elements_yaml = {"elements": {}}
    for alias, meta in recorded_elements.items():
        elements_yaml["elements"][alias] = {
            "displayName": meta["automationId"],
            "controlType": meta["controlType"],
            "parentAlias": alias.split(".")[0] + ".MainWindow",
            "defaultTimeout": 10,
            "tags": ["recorded", "needs-review"],
            "strategies": {
                "FlaUI": {
                    "searchBy": "AutomationId",
                    "value": meta["automationId"],
                    "scope": "Descendant",
                },
                # WPFSpy / Sikuli strategies intentionally omitted — a
                # human reviewer adds these if the control turns out to
                # need a fallback (see docs/RECORDER_GUIDE.md).
            },
        }
    out_path = os.path.join(_REPO_ELEMENTS_DIR, out_file)
    with open(out_path, "w") as f:
        yaml.dump(elements_yaml, f, sort_keys=False, default_flow_style=False)
    print(f"[Converter] Wrote draft Element Repository -> {out_path}")
    return out_path


def generate_step_repository(recorded_steps: dict, out_file="recorded_draft_steps.yaml"):
    steps_yaml = {"steps": {}}
    for alias, meta in recorded_steps.items():
        entry = {"step": meta["step"]}
        if meta["step"] == "ValueStep":
            entry["parameters"] = [{"name": "text", "type": "string", "required": True}]
        else:
            entry["parameters"] = []
        steps_yaml["steps"][alias] = entry
    out_path = os.path.join(_REPO_STEPS_DIR, out_file)
    with open(out_path, "w") as f:
        yaml.dump(steps_yaml, f, sort_keys=False, default_flow_style=False)
    print(f"[Converter] Wrote draft Step Repository -> {out_path}")
    return out_path


def generate_draft_test_script(recorded_sequence: list, out_file="draft_recorded_test.robot"):
    lines = [
        "*** Settings ***",
        "Documentation    AUTO-GENERATED by the Recorder/Converter — raw Layer 3 calls.",
        "...              Functionally accurate but NOT YET production quality: add",
        "...              verifications and refactor into Layer 2 reusable modules",
        "...              before committing to the suite (see docs/RECORDER_GUIDE.md).",
        "Library          ../api/DriverAgnosticApi.py",
        "Test Setup       Reset Application",
        "",
        "*** Test Cases ***",
        "Recorded Session Playback",
        "    [Documentation]    Auto-generated from a recorded session.",
    ]
    for event in recorded_sequence:
        alias = event["alias"]
        if event["step"] == "InvokeStep":
            lines.append(f"    Click Element    {alias}")
        else:
            lines.append(f"    Set Element Value    {alias}    {event['value']}")

    out_path = os.path.join(_DRAFT_TESTS_DIR, out_file)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[Converter] Wrote draft Layer 1 test script -> {out_path}")
    return out_path


def convert_all():
    recorded_elements = _load("recorded_elements.json")
    recorded_steps = _load("recorded_steps.json")
    recorded_sequence = _load("recorded_sequence.json")

    element_repo_path = generate_element_repository(recorded_elements)
    step_repo_path = generate_step_repository(recorded_steps)
    draft_script_path = generate_draft_test_script(recorded_sequence)
    return element_repo_path, step_repo_path, draft_script_path


if __name__ == "__main__":
    convert_all()
