using System.Collections.Generic;
using System.Text;
using WpfTestIde.Models;

namespace WpfTestIde.Recording
{
    /// <summary>
    /// Turns a RecordedStep sequence into a Layer 1 Robot Framework test
    /// script — the C# equivalent of recorder/converter.py's
    /// generate_draft_test_script, kept line-for-line consistent with it
    /// so a script generated by this IDE is indistinguishable from one
    /// generated by the Python recorder pipeline.
    /// </summary>
    public static class ScriptGenerator
    {
        public static string Generate(
            IEnumerable<RecordedStep> steps,
            string testCaseName = "Recorded Session Playback",
            string? driver = null,
            string? mode = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("*** Settings ***");
            sb.AppendLine("Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.");
            sb.AppendLine("...              Functionally accurate but NOT YET production quality: consider");
            sb.AppendLine("...              refactoring repeated sequences into Layer 2 reusable modules");
            sb.AppendLine("...              before committing to the suite (see docs/RECORDER_GUIDE.md).");
            sb.AppendLine("Library          ../api/DriverAgnosticApi.py");

            // If a mode is specified (mock or real), set it as active for the test
            if (!string.IsNullOrEmpty(mode))
            {
                sb.AppendLine("Test Setup       Set Mode    " + mode);
            }

            // If a driver is specified (e.g. "WPFSpy"), set it as active for the test
            if (!string.IsNullOrEmpty(driver))
            {
                sb.AppendLine("Test Setup       Set Driver    " + driver);
            }

            sb.AppendLine();
            sb.AppendLine("*** Test Cases ***");
            sb.AppendLine(testCaseName);
            sb.AppendLine("    [Documentation]    Generated by WpfTestIde.");

foreach (var step in steps)
             {
                 if (step.Kind == StepKind.Verify)
                 {
                     sb.AppendLine($"    Verify Element Text    {step.Alias}    {step.Value}");
                     continue;
                 }

                 if (step.Kind == StepKind.VerifyOcr)
                 {
                     sb.AppendLine($"    Get Data Grid Content Ocr    {step.Alias}");
                     continue;
                 }

                 switch (step.Action)
                {
                    case ActionKind.Invoke:
                        sb.AppendLine($"    Click Element    {step.Alias}");
                        break;
                    case ActionKind.SetValue:
                        sb.AppendLine($"    Set Element Value    {step.Alias}    {step.Value}");
                        break;
                    case ActionKind.Toggle:
                        sb.AppendLine($"    Toggle Element    {step.Alias}");
                        break;
                }
            }

            return sb.ToString();
        }
    }
}
