using System.Collections.Generic;
using System.Text;
using WpfTestIde.Models;

namespace WpfTestIde.Recording
{
    /// <summary>
    /// Turns a RecordedStep sequence into a Layer 1 Robot Framework test
    /// script — the C# equivalent of recorder/converter.py's
    /// generate_draft_test_script, kept line-for-line consistent with it
    /// so a script generated by this IDE is indistinguishable from one
    /// generated by the Python recorder pipeline.
    /// </summary>
    public static class ScriptGenerator
    {
        public static string Generate(
            IEnumerable<RecordedStep> steps,
            string testCaseName = "Recorded Session Playback",
            string? driver = null,
            string? mode = null,
            List<string>? recordingModes = null,
            string? appId = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("*** Settings ***");
            sb.AppendLine("Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.");
            sb.AppendLine("...              Functionally accurate but NOT YET production quality: consider");
            sb.AppendLine("...              refactoring repeated sequences into Layer 2 reusable modules");
            sb.AppendLine("...              before committing to the suite (see docs/RECORDER_GUIDE.md).");
            if (recordingModes != null && recordingModes.Count > 0)
            {
                sb.AppendLine("...              Recording modes: " + string.Join(", ", recordingModes));
            }
             sb.AppendLine("Library          ../api/DriverAgnosticApi.py");

             // Combine mode and driver into a single Test Setup
             var setupParts = new List<string>();
             if (!string.IsNullOrEmpty(mode))
                 setupParts.Add(mode);
             if (!string.IsNullOrEmpty(driver))
                 setupParts.Add(driver);

             if (setupParts.Count == 2)
             {
                 sb.AppendLine($"Test Setup       Set Mode And Driver    {setupParts[0]}    {setupParts[1]}");
             }
             else if (setupParts.Count == 1)
             {
                 if (!string.IsNullOrEmpty(mode))
                     sb.AppendLine($"Test Setup       Set Mode    {mode}");
                 if (!string.IsNullOrEmpty(driver))
                     sb.AppendLine($"Test Setup       Set Driver    {driver}");
             }

             // Multi-app: register the attached app if app_id is known
             if (!string.IsNullOrEmpty(appId))
             {
                 sb.AppendLine($"Test Setup       Attach To Application    {appId}    %{{WPFSPY_PROCESS_ID}}    WPFSpy    %{{WPFSPY_PIPE_NAME}}");
             }

             sb.AppendLine();
            sb.AppendLine("*** Test Cases ***");
            sb.AppendLine(testCaseName);
            sb.AppendLine("    [Documentation]    Generated by WpfTestIde.");

            string appIdArg = string.IsNullOrEmpty(appId) ? "" : $"    app_id={appId}";

            foreach (var step in steps)
            {
                if (step.Kind == StepKind.Verify)
                {
                    sb.AppendLine($"    Verify Element Text    {step.Alias}    {step.Value}{appIdArg}");
                    continue;
                }

                if (step.Kind == StepKind.VerifyOcr)
                {
                    sb.AppendLine($"    Get Data Grid Content Ocr    {step.Alias}{appIdArg}");
                    continue;
                }

                switch (step.Action)
                {
                    case ActionKind.Invoke:
                        sb.AppendLine($"    Click Element    {step.Alias}{appIdArg}");
                        break;
                    case ActionKind.SetValue:
                        sb.AppendLine($"    Set Element Value    {step.Alias}    {step.Value}{appIdArg}");
                        break;
                    case ActionKind.Toggle:
                        sb.AppendLine($"    Toggle Element    {step.Alias}{appIdArg}");
                        break;
                }
            }

            return sb.ToString();
        }
    }
}
