*** Settings ***
Documentation    AUTO-GENERATED by the Recorder/Converter — raw Layer 3 calls.
...              Functionally accurate but NOT YET production quality: add
...              verifications and refactor into Layer 2 reusable modules
...              before committing to the suite (see docs/RECORDER_GUIDE.md).
Library          ../api/DriverAgnosticApi.py
Test Setup       Reset Application

*** Test Cases ***
Recorded Session Playback
    [Documentation]    Auto-generated from a recorded session.
    Set Element Value    LoginPage.txtUsername    user1
    Set Element Value    LoginPage.txtPassword    Pass@123
    Click Element    LoginPage.btnSubmit
    Set Element Value    OrdersPage.cmbSku    SKU-2002
    Set Element Value    OrdersPage.txtQty    3
    Click Element    OrdersPage.btnCreateOrder
