*** Settings ***
Documentation    AUTO-GENERATED by WpfTestIde — raw Layer 3 calls.
...              Functionally accurate but NOT YET production quality: consider
...              refactoring repeated sequences into Layer 2 reusable modules
...              before committing to the suite (see docs/RECORDER_GUIDE.md).
...              Recording modes: FlaUI, WPFSpy
Library          ../../TestAutoLayer/api/DriverAgnosticApi.py
Test Setup       Attach To Application    SampleWpfApp    %{WPFSPY_PROCESS_ID}    WPFSpy    %{WPFSPY_PIPE_NAME}

*** Test Cases ***
Recorded Session Playback
    [Documentation]    Generated by WpfTestIde.
    Set Element Value    SampleWpfApp.LoginPage.txtUsername    user1    app_id=SampleWpfApp
    Click Element    SampleWpfApp.LoginPage.btnSubmit    app_id=SampleWpfApp
    Set Element Value    SampleWpfApp.LoginPage.txtUsername        app_id=SampleWpfApp
